version: '3.7'

services:

  inventory-service:
    build: ./inventory
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./inventory/:/app/
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - redis_inventory

  inventory-stream:
    build: ./inventory
    command: python consumer.py
    env_file:
      - .env
    depends_on:
      - redis_stream
      - inventory-service

  payment-service:
    build: ./payment
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./payment/:/app/
    ports:
      - 8002:8000
    env_file:
      - .env
    depends_on:
      - redis_payment

  payment-stream:
    build: ./payment
    command: python consumer.py

    env_file:
      - .env
    depends_on:
      - redis_stream
      - payment-service

  redis_inventory:
    image: redis:7
    container_name: redis_inv_app
    command: --port 5370
    expose:
      - 5370
    ports:
      - 8003:5370

  redis_payment:
    image: redis:7
    container_name: redis_pay_app
    command: --port 5370
    expose:
      - 5370
    ports:
      - 8004:5370

  redis_stream:
    image: redis:7
    container_name: redis_stream
    command: --port 5370
    expose:
      - 5370
    ports:
      - 8005:5370

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - payment-service
      - inventory-service
